# Couchbase DB Server
FROM couchbase AS couchbase
COPY configure.sh /opt/couchbase
EXPOSE 8091,8092,8093,11210
CMD ["/opt/couchbase/configure.sh"]
RUN ["chmod", "+x", "/opt/couchbase/configure.sh"]
RUN ["chmod", "+x", "entrypoint.sh"]
